"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os

from pathlib import Path
from datetime import timedelta


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ['DEBUG']
WHITENOISE_USE_FINDERS = True


INSTALLED_APPS = [
    # Admin Interface Apps
    'admin_interface',
    'colorfield',

    # Default django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Apps
    'core.apps.CoreConfig',
    'accounts.apps.AccountsConfig',

    # Third party apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'corsheaders',
    'django.contrib.sites',
    'rest_framework',
    'rest_framework.authtoken',

    # Media Library
    'easy_thumbnails',
    'filer',
    'mptt',
]

SITE_ID = 1

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# * Password validation
# ? https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# * Custom user model
# ? https://docs.djangoproject.com/en/4.0/topics/auth/customizing/#specifying-a-custom-user-model
# ? https://testdriven.io/blog/django-custom-user-model/

AUTH_USER_MODEL = 'accounts.CustomUser'

# * Internationalization
# ? https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# * Default primary key field type
# ? https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# * Documentation configuration
# ? https://docs.djangoproject.com/en/4.0/topics/email
# ? https://www.geeksforgeeks.org/setup-sending-email-in-django-project/

# *Twilio configuration
# ? https://www.twilio.com/blog/using-twilio-sendgrid-send-emails-python-django

# Email configuration - for development purposes only (Gmail)
# Twilio SendGrid
EMAIL_BACKEND = "sendgrid_backend.SendgridBackend"
FROM_EMAIL = os.environ['SEND_GRID_VERIFY_MAIL']
DEFAULT_FROM_EMAIL = os.environ['SEND_GRID_VERIFY_MAIL']
SENDGRID_ECHO_TO_STDOUT = True
SENDGRID_API_KEY = os.environ['SEND_GRID_API_KEY']
SENDGRID_SANDBOX_MODE_IN_DEBUG = False


# * Django admin interface configuration
X_FRAME_OPTIONS = 'SAMEORIGIN'
SILENCED_SYSTEM_CHECKS = ['security.W019']


# * Django REST framework configuration
REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'dj_rest_auth.jwt_auth.JWTCookieAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 25,
}

# * Django REST auth configuration
# ? https://dj-rest-auth.readthedocs.io/en/latest/
REST_USE_JWT = True

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_CONFIRM_EMAIL_ON_GET = True

# - Simple JWT & COOKIE Names Configuration
JWT_AUTH_COOKIE = 'my-app-auth'
JWT_AUTH_REFRESH_COOKIE = 'my-refresh-token'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

PASSWORD_RESET_TIMEOUT = 900          # 900 Sec = 15 Min


# * Django CORS configuration
# ? For more information see: https://github.com/adamchainz/django-cors-headers

# CORS_ORIGIN_WHITELIST = (
#     'http://localhost:3000',
#     'http://localhost:8000',
# )
# CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = True

# * Media Library configuration
# ? https://django-filer.readthedocs.io/en/latest/index.html
# ? https://pypi.org/project/django-filer/

THUMBNAIL_PROCESSORS = [
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    'easy_thumbnails.processors.scale_and_crop',
    'filer.thumbnail_processors.scale_and_crop_with_subject_location',
    'easy_thumbnails.processors.filters',
]

FILER_CANONICAL_URL = 'sharing/'

# * NginxXAccelRedirectServer
# ? https://django-filer.readthedocs.io/en/latest/secure_downloads.html
# ? https://django-filer.readthedocs.io/en/latest/secure_downloads.html#nginxxaccelredirectserver

# FILER_SERVERS = {
#     'private': {
#         'main': {
#             'ENGINE': 'filer.server.backends.nginx.NginxXAccelRedirectServer',
#             'OPTIONS': {
#                 'location': '/path/to/smedia/filer',
#                 'nginx_location': '/nginx_filer_private',
#             },
#         },
#         'thumbnails': {
#             'ENGINE': 'filer.server.backends.nginx.NginxXAccelRedirectServer',
#             'OPTIONS': {
#                 'location': '/path/to/smedia/filer_thumbnails',
#                 'nginx_location': '/nginx_filer_private_thumbnails',
#             },
#         },
#     },
# }

# * ApacheXSendfileServer
# ? https://django-filer.readthedocs.io/en/latest/secure_downloads.html
# ? https://django-filer.readthedocs.io/en/latest/secure_downloads.html#apachexsendfileserver

# FILER_SERVERS = {
#     'private': {
#         'main': {
#             'ENGINE': 'filer.server.backends.xsendfile.ApacheXSendfileServer',
#         },
#         'thumbnails': {
#             'ENGINE': 'filer.server.backends.xsendfile.ApacheXSendfileServer',
#         },
#     },
# }
